cd /opt;sleep 3;
wget https://download.configserver.com/csf.tgz;sleep 3;
tar -xzf csf.tgz;sleep 3;
cd csf;sleep 3;
sh install.sh;sleep 3;
rm -rf /opt/csf;sleep 3;
rm -rf /opt/csf.tgz;sleep 3;
cd ~;sleep 3;
systemctl enable csf;sleep 3;
systemctl enable lfd;sleep 3;
service csf start;sleep 3;
service lfd start;sleep 3;
perl /usr/local/csf/bin/csftest.pl;sleep 3;
systemctl enable csf;sleep 3;
systemctl enable lfd;sleep 3;
service csf start;sleep 3;
service lfd start;sleep 3;
